### ISSUE TITLE
How to pass arguments to boilermake

### ISSUE THREAD

**Issue by ksl67** [dmoulding/boilermake#13]
Hi,

I'm new to `make` and after a lot of research I stumbled across boilermake and have implemented it successfully on my project. So, thanks for sharing.

I build a release version of my project by default. I would like to know how to build a debug version of my project by supplying a command line argument such as `debug`. E.g.

`make debug`

which changes some of the compiler options set in `CXXFLAGS` in my top-level makefile.

However, I've not been able to get this to work.

Can you provide an example?

TIA

**Comment by mzemb** [comment]
It's not an exact response, but I think you can have it two ways:

1) pass an argument to make: > make DEBUG=1 which you can use as $(VERBOSE) in you makefiles
Something like:
ifeq ($(debug),1)
	CXXFLAGS:=-O0 -g
else
	CXXFLAGS:=-O3
endif

2) define two differents tagets to make, and you'll go with > make release or > make debug
I believe the simplest way to achieve this is to have to .mk files.

Hope this helps,

Regards,

Michael

**Comment by ksl67** [comment]
Hi Michael,

Thanks for the reply. 

I managed to get option 1 working. Thanks.

For option 2, when I add a new target as described in [this](http://stackoverflow.com/a/1536681/820657) example, it looks like some kind of recursion is going on.

**Comment by mzemb** [comment]
Well, boilermake uses recursion, so maybe that's what you see.
The principle is that the main makefile will parse all "submakefiles" you write and generate dynamically all rules.

**Comment by ksl67** [comment]
Thankyou @mzemb .
