### ISSUE TITLE
Invoke unit tests after building target

### ISSUE THREAD

**Issue by ksl67** [dmoulding/boilermake#14]
Hi,

I'm using `boilermake` to build a unit test suite. After the target has been built successfully I would like the unit tests to be executed. 

I have achieved this so far by using `TGT_POSTMAKE` in `main.mk` to specify that the target is executed after it is built.

```
TGT_POSTMAKE := \
    echo Running unit tests; \
       		cd .. && \
       		targets/my-test-suite

```

When I type `make` the unit test suite is built, if it is out of date, and then executed. If I type `make` again, it informs me that`Nothing to be done for 'all'`.

I would like to be able to run the unit tests even when the target is up to date. How do I achieve this? Even better if I could achieve it by typing `make test`.

Is this possible?

**Comment by mzemb** [comment]
That's not a boilermake issue and the normal behaviour of make: only build the target if it's dependencies are out of date. Why do you want to run the test again if you didn't change anything in your binaries to test ?

Most of the time it means your tests should be rethinked/redesigned, but if you really want it, you can specifiy to make that you want rebuilt it every time - it's done by the _PHONY_ keywoard.

In your case I'll add a rule that should be more or less:
```
.PHONY: test.ok
test.ok: build/test.bin
    bash $^ > $@
```

This way, make test.ok will be executed every time.

**Comment by ksl67** [comment]
Thanks for your reply @mzemb.

I don't really follow your answer so I tried putting the following into `main.mk` but the tests are executed every time, without an update, whether I enter `make` or `make test` at the command line.

```
.PHONY: test
test:
    cd .. && \
    targets/my-test-suite
```

**Comment by ksl67** [comment]
I figured it out. By adding the following to `main.mk` I get the behaviour I want.

    .DEFAULT_GOAL := all
    
    .PHONY: test
    test: all
        cd .. && \
        targets/my-test-suite

Entering `make` will update and run the tests if anything has changed. 

Entering `make test` will update and run the tests if anything has changed or just run the unit tests if nothing has changed.
