### ISSUE TITLE
Special Rules for Generating Objects

### ISSUE THREAD

**Issue by Piping** [dmoulding/boilermake#16]
Hi,

Is there a way to generate object files manually with some special actions? like before `gcc -c` and post rule? 

Right now it uses implicit rules for all kinds of object file

**Comment by nispio** [comment]
What is your goal? Is this something you are trying to do as part of a normal workflow? Or just a one-off task? Spending time thinking about intermediate build products seems to be the antithesis of a build system like boilermake. But knowing what your end goal is might make a good solution more obvious.

Also, I'm a little confused what you mean by "before `gcc -c`" since that command produces object files.

**Comment by Piping** [comment]
@nispio Thanks for response. I am trying to build a non-recursive makefile that fits complex system.

Because I am working quite low level stuff, sometimes I need to auto generate code before I pass those auto-generated file to gcc.

For target binary it can be done by adding some hook before using gcc, but I am not sure how to do it with object files, since not all objects need that special treatments.

if I am understand correctly, it is important to keep a namespace clean for non-recursive approach since makefile does not have the concept of scope like other programming languages.

**Comment by nispio** [comment]
There are lots of assumptions made by boilermake, which is precisely why it is able to be so simple.  If you are breaking enough of those assumptions, you may have to make non-trivial modifications to boilermake itself.

Depending on how you autogenerate code, you may be able to just add a normal GNU Makefile recipe for how those source files are generated.  That way, at build time, the make system will not only know that a source file is required for a target, but will also know how to update or create that source as necessary.

**Comment by Piping** [comment]
@nispio I totally agree, in the worst case, I need to create a rule that is inevitably existed in the global namespace.

The problem here is that boliterplate does not manage objects files in the depdency directly but only via target/sources.  And I have the situation that the creation of one object file depends on other objects, and `other objects`  + that special objects are needed for the final target.

Anyway to do it that is compatible to current mechanism? Since user-defined own rule will appears before `all`.

**Comment by nispio** [comment]
I think you will find that your use case is not well supported. However, you should be able to define an explicit recipe for your auto generated sources. You should be able to leave the target `all` as the default target by setting `.DEFAULT_GOAL` as described here: https://www.gnu.org/software/make/manual/html_node/Special-Variables.html#Special-Variables

**Comment by Piping** [comment]
@nispio Thanks.
