### ISSUE TITLE
How to use boilermaker, I'm new to make and I didn't found any documents to read about how to use boilermaker

### ISSUE THREAD

**Issue by chandanchan0086** [dmoulding/boilermake#19]

**Comment by mzemb** [comment]
Hi.

Boilermake is indeed meant for people with make experience.

You can start by reading the paper that describe in details the problem that boilermake is solving:
"recursive makefiles considered harmful"
https://web.archive.org/web/20070205211740/http://aegis.sourceforge.net/auug97.pdf

It goes into a lot of details and explanations suitable for a beginner.

Then I suggest you clone this repository locally, go into the test-app directory, and use the autocomplete feature by typing:
> make <tab>
This will list the different targets you can construct.

**Comment by chandanchan0086** [comment]
Hi @mzemb thank you for the information. okay, I will read that document.
